// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KKSSRJ2_5Up53CPrrP0je3v1Sih2Ers',
    appId: '1:565416077852:web:30db277083604253218dd9',
    messagingSenderId: '565416077852',
    projectId: 'ourclasscalendar-90a57',
    authDomain: 'ourclasscalendar-90a57.firebaseapp.com',
    storageBucket: 'ourclasscalendar-90a57.firebasestorage.app',
    measurementId: 'G-QW578YMLE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLysFOnW7jITbGr9xXyajy9ZrQdnm0JNk',
    appId: '1:565416077852:android:1513ee53e814f4fb218dd9',
    messagingSenderId: '565416077852',
    projectId: 'ourclasscalendar-90a57',
    storageBucket: 'ourclasscalendar-90a57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDnNoz43Vtzm8oeaJ_E_yEO8x82zNRusU',
    appId: '1:565416077852:ios:85e8bac97a5df16c218dd9',
    messagingSenderId: '565416077852',
    projectId: 'ourclasscalendar-90a57',
    storageBucket: 'ourclasscalendar-90a57.firebasestorage.app',
    iosBundleId: 'com.example.classCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDnNoz43Vtzm8oeaJ_E_yEO8x82zNRusU',
    appId: '1:565416077852:ios:85e8bac97a5df16c218dd9',
    messagingSenderId: '565416077852',
    projectId: 'ourclasscalendar-90a57',
    storageBucket: 'ourclasscalendar-90a57.firebasestorage.app',
    iosBundleId: 'com.example.classCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KKSSRJ2_5Up53CPrrP0je3v1Sih2Ers',
    appId: '1:565416077852:web:30db277083604253218dd9',
    messagingSenderId: '565416077852',
    projectId: 'ourclasscalendar-90a57',
    authDomain: 'ourclasscalendar-90a57.firebaseapp.com',
    storageBucket: 'ourclasscalendar-90a57.firebasestorage.app',
    measurementId: 'G-QW578YMLE9',
  );

}